### ISSUE TITLE
cannot get cancel to work

### ISSUE THREAD

**Issue by peterennis** [JoshuaKGoldberg/emojisplosion#14]
Ionic/Angular project. Latest versions.

Specific code here: https://github.com/peterennis/ae-monorepo-ng/blob/master/packages/ae-i4/src/app/pages/home/home.page.ts

I expect the cancel to happen on leaving the page but it does not trigger.
The ionViewDidLeave is activated as the log is displayed.

Is there some ts foo I am missing?

Based on the readme example:

![Capture681](https://user-images.githubusercontent.com/140737/65933154-46f47880-e3c5-11e9-807d-a702389758f6.png)

My goal is to have play/pause/continue/stop operations.

![aemoji-cancel-test](https://user-images.githubusercontent.com/140737/65933172-583d8500-e3c5-11e9-8f78-5b0a264b0c49.gif)

**Comment by JoshuaKGoldberg** [comment]
@peterennis it's exciting to see your use case coming together :smile: but the code right now never calls `cancel`:

> ```ts
> // If the count down is over then start continuous explosions
> if (countDown < 0) {
>   clearInterval(x);
>   document.getElementById('demo').innerHTML = '&nbsp;&nbsp;&nbsp;EXPLODING NOW !!!';
>   // Commence explosions!
>   const { cancel } = emojisplosions();
> }
> ```

`cancel` seems to be working right now from trying it out on 1.2.0. If this is still an issue for you, could you post a code snippet or link with the broken behavior?

**Comment by peterennis** [comment]
@JoshuaKGoldberg 

I setup a repo you can clone: https://github.com/peterennis/ae-i4

The cancel is implemented here: https://github.com/peterennis/ae-i4/blob/master/src/app/pages/home/home.page.ts#L56-L57

This event activates on leaving the page but does not call cancel.

cancel is set in the module here: https://github.com/peterennis/ae-i4/blob/master/src/app/pages/home/home.page.ts#L11

![Capture682](https://user-images.githubusercontent.com/140737/66018865-a9b54500-e495-11e9-9071-6275db50e685.png)

**Comment by JoshuaKGoldberg** [comment]
Ah, the problem isn't in emojisplosion's code base. It's in yours 😜

You never assign `cancel` to anything, so `this.cancel` is never set. Fixed and explained in more detail by https://github.com/peterennis/ae-i4/pull/2.

**Comment by peterennis** [comment]
@JoshuaKGoldberg 

It is now working here: https://github.com/peterennis/ae-i4/blob/master/src/app/pages/home/home.page.ts

Thanks 👍
