### ISSUE TITLE
Switch from TSLint to typescript-eslint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/emojisplosion#15]
This repository still uses TSLint, which is being deprecated: https://github.com/palantir/tslint/issues/4534. It'd be great to move it over to [typescript-eslint](http://typescript-eslint.io) to no longer use deprecated packages.

Protip: [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config) is the recommended package to do so!

**Comment by florian42** [comment]
I would like to help out with this one :)

**Comment by florian42** [comment]
Im missing privileges to push :(
Moreover, there seem to be some issues regarding the js files. Eslint reports for exaple:

/Users/florian/Source/github/hacktober/emojisplosion/src/utils.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: /Users/florian/Source/github/hacktober/emojisplosion/src/utils.js.
The file must be included in at least one of the projects provided

✖ 14 problems (14 errors, 0 warnings)

It basically reports this for all js files.

**Comment by JoshuaKGoldberg** [comment]
> Im missing privileges to push :(

Yup, you'll need to [fork the repository](https://help.github.com/en/articles/fork-a-repo) and [send a pull request](https://help.github.com/en/articles/creating-a-pull-request).

> 0:0 error Parsing error
> The file must be included in at least one of the projects provided

Sounds like the ESLint configuration hasn't been set up properly to exclude `.js` files? https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser suggests including `src/**/*.ts` or similar includes, and only including `.js` files if needed (which is not the case here).

**Comment by florian42** [comment]
It also mentions:

> TypeScript will ignore files with duplicate filenames in the same folder (for example, src/file.ts and src/file.js). TypeScript purposely ignore all but one of the files, only keeping the one file with the highest priority extension (the extension priority order (from highest to lowest) is .ts, .tsx, .d.ts, .js, .jsx). For more info see #955.

So it shouldn't even consider the js files in the first place?

The JS files arent referenced in any configuration. The eslint config points to the tsconfig.

Currently the configs look like this:

`{
  "compilerOptions": {
    "declaration": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "dom",
      "es5",
      "es2015.collection"
    ],
    "module": "amd",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "pretty": true,
    "strict": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "./src/**/*.ts"
  ]
}`

eslint config:

`module.exports = {
  "env": {
    "browser": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint",
    "@typescript-eslint/tslint"
  ],
  "rules": {
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/ban-ts-ignore": "error",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/class-name-casing": "error",
    "@typescript-eslint/explicit-member-accessibility": [
      "error",
      {
        "overrides": {
          "constructors": "off"
        }
      }
    ],
    "@typescript-eslint/indent": "error",
    "@typescript-eslint/interface-name-prefix": "error",
    "@typescript-eslint/member-delimiter-style": "error",
    "@typescript-eslint/no-angle-bracket-type-assertion": "error",
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-extraneous-class": "error",
    "@typescript-eslint/no-for-in-array": "error",
    "@typescript-eslint/no-inferrable-types": "error",
    "@typescript-eslint/no-misused-new": "error",
    "@typescript-eslint/no-namespace": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-object-literal-type-assertion": "error",
    "@typescript-eslint/no-param-reassign": "off",
    "@typescript-eslint/no-parameter-properties": "error",
    "@typescript-eslint/no-require-imports": "error",
    "@typescript-eslint/no-this-alias": "error",
    "@typescript-eslint/no-triple-slash-reference": "error",
    "@typescript-eslint/no-unnecessary-qualifier": "error",
    "@typescript-eslint/no-unnecessary-type-assertion": "error",
    "@typescript-eslint/no-use-before-declare": "off",
    "@typescript-eslint/no-var-requires": "error",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-function-type": "error",
    "@typescript-eslint/prefer-interface": "error",
    "@typescript-eslint/prefer-namespace-keyword": "error",
    "@typescript-eslint/promise-function-async": "error",
    "@typescript-eslint/restrict-plus-operands": "error",
    "@typescript-eslint/type-annotation-spacing": "error",
    "@typescript-eslint/unbound-method": "error",
    "@typescript-eslint/unified-signatures": "error",
    "arrow-body-style": "off",
    "arrow-parens": [
      "error",
      "as-needed"
    ],
    "class-methods-use-this": "error",
    "complexity": "error",
    "constructor-super": "error",
    "curly": "error",
    "default-case": "error",
    "dot-notation": "error",
    "eol-last": "error",
    "guard-for-in": "error",
    "linebreak-style": "off",
    "max-classes-per-file": [
      "error",
      1
    ],
    "max-lines": [
      "error",
      1000
    ],
    "member-ordering": "error",
    "new-parens": "error",
    "newline-per-chained-call": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-cond-assign": "error",
    "no-console": "error",
    "no-debugger": "error",
    "no-duplicate-case": "error",
    "no-empty": "off",
    "no-empty-functions": "off",
    "no-eval": "error",
    "no-extra-bind": "error",
    "no-irregular-whitespace": "error",
    "no-magic-numbers": "off",
    "no-multiple-empty-lines": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-plusplus": [
      "error",
      {
        "allowForLoopAfterthoughts": true
      }
    ],
    "no-return-await": "error",
    "no-sequences": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-undef-init": "error",
    "no-unsafe-finally": "error",
    "no-unused-labels": "error",
    "no-useless-constructor": "error",
    "no-var": "error",
    "object-shorthand": "error",
    "one-var": "error",
    "prefer-const": "error",
    "prefer-object-spread": "error",
    "prefer-template": "error",
    "quote-props": [
      "error",
      "consistent-as-needed"
    ],
    "radix": "error",
    "space-before-function-parent": [
      "error",
      {
        "anonymous": "never",
        "asyncArrow": "always",
        "constructor": "never",
        "method": "never",
        "named": "never"
      }
    ],
    "use-isnan": "error",
    "yoda": "error",
    "@typescript-eslint/tslint/config": [
      "error",
      {
        "rules": {
          "align": [
            true,
            "parameters",
            "arguments",
            "statements",
            "elements",
            "members"
          ],
          "comment-type": [
            true,
            "singleline",
            "multiline",
            "doc",
            "directive"
          ],
          "encoding": true,
          "file-name-casing": [
            true,
            "camel-case"
          ],
          "import-spacing": true,
          "invalid-void": true,
          "jsdoc-format": [
            true,
            "check-multiline-start"
          ],
          "match-default-export-name": true,
          "max-line-length": [
            true,
            175
          ],
          "newline-before-return": true,
          "no-async-without-await": true,
          "no-boolean-literal-compare": true,
          "no-default-export": true,
          "no-default-import": true,
          "no-duplicate-imports": true,
          "no-duplicate-variable": [
            true,
            "check-parameters"
          ],
          "no-floating-promises": true,
          "no-for-in": true,
          "no-implicit-dependencies": true,
          "no-import-side-effect": true,
          "no-inferred-empty-object-type": true,
          "no-mergeable-namespace": true,
          "no-null-keyword": true,
          "no-null-undefined-union": true,
          "no-promise-as-boolean": true,
          "no-redundant-jsdoc": true,
          "no-reference-import": true,
          "no-restricted-globals": true,
          "no-shadowed-variable": true,
          "no-submodule-imports": true,
          "no-tautology-expression": true,
          "no-trailing-whitespace": true,
          "no-unnecessary-callback-wrapper": true,
          "no-unsafe-any": true,
          "no-unused-expression": true,
          "no-void-expression": true,
          "number-literal-format": true,
          "one-line": [
            true,
            "check-catch",
            "check-else",
            "check-finally",
            "check-open-brace",
            "check-whitespace"
          ],
          "only-arrow-functions": true,
          "ordered-imports": [
            true,
            {
              "grouped-imports": true,
              "import-sources-order": "case-insensitive",
              "named-imports-order": "case-insensitive",
              "module-source-path": "full"
            }
          ],
          "prefer-conditional-expression": true,
          "prefer-readonly": true,
          "prefer-switch": true,
          "prefer-while": true,
          "quotemark": [
            true,
            "double",
            "avoid-escape",
            "avoid-template"
          ],
          "return-undefined": true,
          "semicolon": [
            true,
            "always"
          ],
          "space-within-parens": [
            true,
            0
          ],
          "static-this": true,
          "strict-boolean-expressions": true,
          "strict-string-expressions": true,
          "strict-type-predicates": true,
          "switch-final-break": true,
          "trailing-comma": [
            true,
            {
              "esSpecCompliant": true,
              "multiline": "always",
              "singleline": "never"
            }
          ],
          "triple-equals": true,
          "unnecessary-else": true,
          "use-default-type-parameter": true,
          "whitespace": [
            true,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-module",
            "check-separator",
            "check-type",
            "check-typecast",
            "check-preblock",
            "check-type-operator",
            "check-rest-spread"
          ]
        }
      }
    ]
  }
};
`

**Comment by JoshuaKGoldberg** [comment]
Could you send a pull request @florian42? It'll be easier to review & bugfix from there. 😄

**Comment by florian42** [comment]
I create a pull request: https://github.com/JoshuaKGoldberg/emojisplosion/pull/16
