### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/emojisplosion#44]
This repository is from back when I used `.travis.yml` as the build manager for all my projects... it's been a while!

**Comment by fuadop** [comment]
Hey @JoshuaKGoldberg  👋🏾 , is this project still maintained? can I work on this ?to convert the travis to github actions.

**Comment by JoshuaKGoldberg** [comment]
Hi @fuadop! Yup, emojisplosion is still maintained -- it's just been a while since it's needed any updates 😄.

This probably isn't a great issue for you to tackle because CI is hard to set up from someone who doesn't own a repo (or isn't in an organization that does). But if there are other issues & feature requests you'd like to file, I'd love that! Otherwise #1 is still open if you want a fun challenge :)

**Comment by JoshuaKGoldberg** [comment]
This was done.
