### ISSUE TITLE
This library needs github pages

### ISSUE THREAD

**Issue by svrooij** [JoshuaKGoldberg/emojisplosion#45]
Or just any other server, just to open the demos in the browser without cloning the repo.

**Comment by JoshuaKGoldberg** [comment]
💯, agreed! I'll be free to get them set up in a couple of weeks. It'd be great to get the default demos pages deployed!

**Comment by svrooij** [comment]
I saw your post about quitting your job and going open-source developer for some time. You got me curious about this project. Wanted to check it out. Have to get my laptop to clone the code and try it out.

A simple Github page would be awesome.
