### ISSUE TITLE
🚀 Feature: Add newer emojis

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/emojisplosion#55]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emojisplosion/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This repo's emoji list was first filled out in July of 2018 (8c0e417674588d20e7311f1727bd11feb17fd69f). A lot of years of emoji have come out since then. I'd like to add more of them.

**Comment by ArielaRfa** [comment]
Hi,i add a new emoji in a "emoji.ts"

**Comment by JoshuaKGoldberg** [comment]
Whoops, meant to note this was fixed by #138.
